### ISSUE TITLE
minerva_var_new need be called in other situation

### ISSUE THREAD

**Issue by slowpy** [akat1/minerva_lib#9]
minerva_var_new should be called before minerva_func_get.

I test use a function with int pointer arg,and I found it never be called.
It be  filtered by minerva_func_qualify  . cause var[arg_type] == 0

I modify toy.h toy.c and toy.mi

**Comment by psie** [comment]
I am not sure I understand what you mean.

Is that the case that you have two functions, say:

`int zero();
void foo(int *ptr);`

and would like the address the result of the first be used as an argument of the second?

Could you possibly provide a piece of code explaining the issue?

Thanks.

**Comment by slowpy** [comment]
In the project,there is a demo(minva_lib/target/toy).I do nothing just run it,it run ok.
Then I modify the demo like:
int crashme(int x);  //-----------------original
int crashme(int *x) ///----------------I modified

this func (int crashme(int *x)) never be executed.

I debug it and found the reason,

minerva_func_get this func choose one func for test(from func_arr);

a func that have opptunity for execute,must be checked by minerva_func_qualify ,
the func (int crashme(int *x)) its arg c __minerva_int_ptr_t len is 0;

code is here 
 minerva_lib/core/minerva_func.c   //line 102   here return .

minerva_var_new this func add vars->len[]

**Comment by psie** [comment]
I see your point.
This is a valuable idea and I think we could make it work the way you suggested.
Thanks again, I'll reply as soon as we code it.

**Comment by akat1** [comment]
I've added -W option to compiler to warn user if any function from the configuration set is unreachable. Change: 72910033a9a00e13d3713de19e04b6e5a49d523e
